@startuml
participant McpClient as ":MCPClient"
participant UserManagement as ":UserManagement"
participant ApiManagement as ":ApiManagement"
autonumber

[o->> McpClient: list existing MCP Tools
activate McpClient
McpClient -> UserManagement: GET users/{id}/apis
activate UserManagement
return API_ACCESS

group loop (for every API ID)
McpClient -> ApiManagement: GET apis/{id}
activate ApiManagement
return spec

alt API ic active
McpClient -> McpClient: mark as active
activate McpClient
return
else
McpClient -> McpClient: mark as inactive
activate McpClient
return
end

end
@enduml