openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8082
    description: Generated server url
paths:
  /apis/{id}:
    get:
      tags:
        - api-controller
      operationId: getApi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: group
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Api'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
    put:
      tags:
        - api-controller
      operationId: putApi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: group
          in: query
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Api'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
    delete:
      tags:
        - api-controller
      operationId: deleteApi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: group
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /apis:
    get:
      tags:
        - api-controller
      operationId: getApis
      parameters:
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: group
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Api'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
    post:
      tags:
        - api-controller
      operationId: postApi
      parameters:
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: group
          in: query
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Api'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /apis/{id}/invoke:
    post:
      tags:
        - api-controller
      operationId: invokeApi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: group
          in: query
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvokeQuery'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InvokeResult'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
components:
  schemas:
    Api:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        version:
          type: string
        format:
          type: string
        fileType:
          type: string
        spec:
          type: string
        token:
          type: string
    InvokeQuery:
      type: object
      properties:
        requestType:
          type: string
          enum:
            - POST
            - PUT
            - GET
            - PATCH
            - DELETE
        requestPath:
          type: string
        header:
          type: object
          additionalProperties:
            type: string
        body:
          type: string
        requestParam:
          type: object
          additionalProperties:
            type: string
        pathParam:
          type: object
          additionalProperties:
            type: string
    InvokeResult:
      type: object
      properties:
        responseCode:
          type: integer
          format: int32
        header:
          type: object
          additionalProperties:
            type: string
        body:
          type: string
